# Notes
# - depends_on is not effective enough to control the dependency

version: '3'
services:
  graph-server:
    build:
      context: .
      dockerfile: Dockerfile-server
      args:
        - VERSION=20.4.0
    image: graph-server:20.4.0
    ports:
      - "7007:7007"
    depends_on:
      - "database"
    volumes:
     - ./graphs:/graphs
     - ./conf/pgx.conf:/etc/oracle/graph/pgx.conf
     - ./conf/server.conf:/etc/oracle/graph/server.conf
     - ./keystore.p12:/opt/oracle/keystore.p12
    networks:
      - network
    command: >
      expect -c "
        set timeout 3
        spawn start-server --secret-store /opt/oracle/keystore.p12
        expect \"enter password for keystore /opt/oracle/keystore.p12:\"
        send \"oracle\n\"
        interact
      "
    stdin_open: true
    tty: true
  graph-client:
    build:
      context: .
      dockerfile: Dockerfile-client
      args:
        - VERSION=20.4.0
    image: graph-client:20.4.0
    volumes:
     - ./graphs:/graphs
     - ./keystore.p12:/opt/oracle/keystore.p12
    networks:
      - network
    tty: true
  zeppelin:
    image: apache/zeppelin:0.8.2
    ports:
      - "8080:8080"
    depends_on:
      - "graph-server"
    volumes:
      - ./graphs:/graphs
      - ./zeppelin/conf/zeppelin-site.xml:/zeppelin/conf/zeppelin-site.xml
      - ./zeppelin/interpreter/pgx:/zeppelin/interpreter/pgx
      - ./zeppelin/notebook:/zeppelin/notebook
    networks:
      - network
  database:
    image: oracle/database:19.3.0-ee
    ports:
      - "1521:1521"
    volumes:
      - ./graphs:/graphs
      - ./scripts:/home/oracle/scripts
    environment:
      - ORACLE_PWD=Welcome1
    networks:
      - network
  jupyter:
    user: root
    build:
      context: .
      dockerfile: Dockerfile-jupyter
      args:
        - VERSION=20.4.0
    image: jupyter:20.4.0
    volumes:
     - ./graphs:/graphs
     - ./jupyter/work:/home/jovyan/work
    ports:
      - "8888:8888"
    networks:
      - network
networks:
  network:
